name: clang-format Check
on: [pull_request]
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
    
    - name: 🌐 Downloading .clang-format from TheAtlasEngine
      run: wget https://github.com/engine3d-dev/TheAtlasEngine/blob/main/.clang-format -O .clang-format
    
    - uses: actions/checkout@v4
    - name: Run clang-format style check for C/C++/Protobuf programs.
      uses: jidicula/clang-format-action@v4.14.0
      with:
        clang-format-version: 19
        check-path: '.'
        fallback-style: 'LLVM' # optional
