name: 🛠️ Continous Integration

on: [pull_request]

jobs:
  windows:
    uses: ./.github/workflows/windows.yml
    secrets: inherit

  linux:
    uses: ./.github/workflows/linux.yml
    secrets: inherit

  mac-armv8:
    uses: ./.github/workflows/mac.yml
    secrets: inherit