name: 🛠️ CI

on: [pull_request]

jobs:
  clang-format:
    uses: engine3d-dev/ci/.github/workflows/clang-format.yml@main
    with:
      package_name: "vulkan-cpp"
      version: "6.0"
    secrets: inherit

  windows:
    uses: engine3d-dev/ci/.github/workflows/windows.yml@main
    with:
      package_name: "vulkan-cpp"
      version: "6.0"
    secrets: inherit

  linux:
    uses: engine3d-dev/ci/.github/workflows/linux.yml@main
    with:
      package_name: "vulkan-cpp"
      version: "6.0"
    secrets: inherit

  mac-armv8:
    uses: engine3d-dev/ci/.github/workflows/mac.yml@main
    with:
      package_name: "vulkan-cpp"
      version: "6.0"
    secrets: inherit