name: cpp-linter

on: [pull_request]


jobs:
  cpp-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: '' # Disables clang-format so it strictly runs clang-tidy
          tidy-checks: '.clang-tidy'
          extensions: 'cpp,cppm,h,hpp' # common C++ file extensions
          # files-changed-only: true
          thread-comments: ${{ github.event_name == 'pull_request' && 'update' }}
          # Ensure clang-tidy knows how to parse modern C++ headers/modules without a compile_commands.json
          extra-args: '-Wall -Wextra -Werror std=c++23'

      - name: Failed fast?!
        # Does a check if any of the given clang-tidy checks failed!
        if: steps.linter.outputs.checks-failed != '0'
        run: |
          echo "Failed clang-tidy linters check"
          echo "Total violations reported: ${{ steps.linter.outputs.checks-failed }}"
          exit 1