name: cpp-linter

on: [pull_request]


jobs:
  cpp-linter:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: cpp-linter/cpp-linter-action@main
        id: linter
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: ''
          tidy-checks: '.clang-tidy'
          extensions: 'cpp, cppm'
          files-changed-only: true
          thread-comments: false
          extra-args: '-std=c++23'

      - name: Fail fast?!
        if: ${{ steps.linter.outputs.checks-failed > 0 }}
        run: |
          echo "some linter checks failed. ${{ steps.linter.outputs.checks-failed }}"
          # for actual deployment
          exit 1