name: Windows

# workflow_call to have linux.yml be able to be invoked by ci.yml
on: [workflow_call]


jobs:
  setup-environments:
    uses: ./.github/workflows/platform-config.yml
    secrets: inherit
  windows-build:
      needs: setup-environments
      runs-on: windows-latest
      steps:
        - uses: actions/checkout@v4

        - name: Restore Windows Environment Cache
          uses: actions/cache@v4
          with:
            path: |
              AppData\Local\pip\Cache
              .conan2
              vulkan_sdk
            key: ${{ needs.setup-environments.outputs.cache-key-windows }}

        - name: Expose Tools to Linux Environment
          run: |
            echo "$HOME/.local/bin" >> $GITHUB_PATH
            echo "${{ github.workspace }}/vulkan_sdk/bootstrapped/bin" >> $GITHUB_PATH
            echo "VULKAN_SDK=${{ github.workspace }}/vulkan_sdk/bootstrapped" >> $GITHUB_ENV


        - name: Creating Release build for vulkan-cpp
          shell: pwsh
          run: conan atlas create . -s build_type=Release
        
        - name: Creating Debug build for vulkan-cpp
          shell: pwsh
          run: conan atlas create . -s build_type=Debug

        - name: Creating MinSizeRel build for vulkan-cpp
          shell: pwsh
          run: conan atlas create . -s build_type=MinSizeRel